services:
  maulwurf-zettelgenerator:
    build: .
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./static:/static

  nginx:
    build:
      context: .
      dockerfile: nginx-docker/Dockerfile
    ports:
      - "80:80"
