# Generated by Django 4.2.20 on 2025-03-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zettel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandidatur',
            name='fakultaetFachschaft',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
