# Generated by Django 5.1.7 on 2025-05-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zettel', '0002_kandidatur_fakultaetfachschaft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kandidatur',
            options={'managed': False},
        ),
    ]
