# Generated by Django 5.1.7 on 2025-05-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zettel', '0003_alter_kandidatur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kandidatur',
            options={'managed': True},
        ),
    ]
